repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: end-of-file-fixer
- repo: https://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/ambv/black
  rev: 21.6b0
  hooks:
  - id: black
    language_version: python3.9
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
